/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.EStatut;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author hp
 */
public class MDIApplication extends javax.swing.JFrame {
    
    private static  MDIApplication instance;
    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion de reclamation");
        this.setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        gestionMenuItem = new javax.swing.JMenu();
        etudiantMenuItem = new javax.swing.JMenuItem();
        ReclamationeMenuItem = new javax.swing.JMenuItem();
        TraitementMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        listEtudiantByStatut = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        actionMenuItem1 = new org.jfree.ui.action.ActionMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gestionMenuItem.setMnemonic('f');
        gestionMenuItem.setText("Gestion");

        etudiantMenuItem.setMnemonic('o');
        etudiantMenuItem.setText("Étudiant");
        etudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiantMenuItemActionPerformed(evt);
            }
        });
        gestionMenuItem.add(etudiantMenuItem);

        ReclamationeMenuItem.setMnemonic('s');
        ReclamationeMenuItem.setText("Réclamation");
        ReclamationeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReclamationeMenuItemActionPerformed(evt);
            }
        });
        gestionMenuItem.add(ReclamationeMenuItem);

        TraitementMenuItem.setMnemonic('a');
        TraitementMenuItem.setText("TraitementRéclamation");
        TraitementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraitementMenuItemActionPerformed(evt);
            }
        });
        gestionMenuItem.add(TraitementMenuItem);

        menuBar.add(gestionMenuItem);

        editMenu.setMnemonic('e');
        editMenu.setText("Statistiques");

        listEtudiantByStatut.setMnemonic('y');
        listEtudiantByStatut.setText("Etudiant par statut");
        listEtudiantByStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEtudiantByStatutActionPerformed(evt);
            }
        });
        editMenu.add(listEtudiantByStatut);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Recherche par etudiant");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        actionMenuItem1.setText("pieChart");
        actionMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(actionMenuItem1);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiantMenuItemActionPerformed
        closeAllInternalFrames();
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        ef.setVisible(true);
        centerInternalFrame(ef);

    }//GEN-LAST:event_etudiantMenuItemActionPerformed

    private void TraitementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraitementMenuItemActionPerformed
        closeAllInternalFrames();
        TraitementRéclamationForm trf= new TraitementRéclamationForm();
        desktopPane.add(trf);
        trf.setVisible(true);
        centerInternalFrame(trf);

    }//GEN-LAST:event_TraitementMenuItemActionPerformed

    private void ReclamationeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReclamationeMenuItemActionPerformed
        closeAllInternalFrames();
        ReclamationForm rf = new ReclamationForm();
        desktopPane.add(rf);
        rf.setVisible(true);
        centerInternalFrame(rf);
    }//GEN-LAST:event_ReclamationeMenuItemActionPerformed

    private void listEtudiantByStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEtudiantByStatutActionPerformed
        closeAllInternalFrames();
        EtudiantByStatut ebs = new EtudiantByStatut();
        desktopPane.add(ebs);
        ebs.setVisible(true);
        centerInternalFrame(ebs);
    }//GEN-LAST:event_listEtudiantByStatutActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        closeAllInternalFrames();
        SearchEtudiant se = new SearchEtudiant();
        desktopPane.add(se);
        se.setVisible(true);
        centerInternalFrame(se);
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void actionMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuItem1ActionPerformed
        closeAllInternalFrames();
        Graph g = new Graph();
        desktopPane.add(g);
        g.setVisible(true);
        centerInternalFrame(g);
    }//GEN-LAST:event_actionMenuItem1ActionPerformed

    private void closeAllInternalFrames() {
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            frame.dispose();
        }
    }
    private void centerInternalFrame(JInternalFrame internalFrame) {
        int x = (desktopPane.getWidth() - internalFrame.getWidth()) / 2;
        int y = (desktopPane.getHeight() - internalFrame.getHeight()) / 2;
        internalFrame.setLocation(x, y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ReclamationeMenuItem;
    private javax.swing.JMenuItem TraitementMenuItem;
    private org.jfree.ui.action.ActionMenuItem actionMenuItem1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem etudiantMenuItem;
    private javax.swing.JMenu gestionMenuItem;
    private javax.swing.JMenuItem listEtudiantByStatut;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
