/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.EStatut;
import beans.Etudiant;
import beans.Reclamation;
import beans.TraitementReclamation;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.EtudiantService;
import services.ReclamationService;
import services.TraitementReclamationService;

/**
 *
 * @author hkoub
 */
public class TraitementRéclamationForm extends javax.swing.JInternalFrame {

    private TraitementReclamationService trs;
    private EtudiantService es;
    private ReclamationService rs;
    private DefaultTableModel model;
    private static int id;

    /**
     * Creates new form TraitementRéclamationForm
     */
    public TraitementRéclamationForm() {
        initComponents();
        trs = new TraitementReclamationService();
        es = new EtudiantService();
        rs = new ReclamationService();
        model = (DefaultTableModel) listeTraitement.getModel();
        loadReclamation();
        loadEtudiant();
        Load();
    }

    void loadReclamation() {
        for (Reclamation r : rs.findAll()) {
            listeReclamation.addItem(r);
        }
    }

    void loadEtudiant() {
        for (Etudiant e : es.findAll()) {
            listeEtudiant.addItem(e);
        }
    }

    void Load() {
        model.setRowCount(0);
        for (TraitementReclamation t : trs.findAll()) {
            model.addRow(new Object[]{t.getEtudiant(), t.getReclamation(), t.getStatut(), t.getCommentaire()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        listeReclamation = new javax.swing.JComboBox();
        listeEtudiant = new javax.swing.JComboBox();
        oui = new javax.swing.JRadioButton();
        non = new javax.swing.JRadioButton();
        bnAdd = new javax.swing.JButton();
        bnUpddate = new javax.swing.JButton();
        bnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeTraitement = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 210, 200));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Traitement des Réclamations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), java.awt.Color.darkGray)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Commentaire :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Statut :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Reclamation :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Etudiant :");

        txtComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentActionPerformed(evt);
            }
        });

        buttonGroup1.add(oui);
        oui.setText("Traitee");
        oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiActionPerformed(evt);
            }
        });

        buttonGroup1.add(non);
        non.setText("non Traitee");
        non.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonActionPerformed(evt);
            }
        });

        bnAdd.setBackground(new java.awt.Color(144, 238, 144));
        bnAdd.setForeground(new java.awt.Color(0, 100, 0));
        bnAdd.setText("Ajouter");
        bnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddActionPerformed(evt);
            }
        });

        bnUpddate.setBackground(new java.awt.Color(102, 102, 255));
        bnUpddate.setForeground(new java.awt.Color(0, 0, 139));
        bnUpddate.setText("Modifier");
        bnUpddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnUpddateActionPerformed(evt);
            }
        });

        bnDelete.setBackground(new java.awt.Color(255, 105, 97));
        bnDelete.setText("Suprimer");
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oui, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(55, 55, 55)
                                .addComponent(listeReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(non)))
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnUpddate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(listeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(listeReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnAdd))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oui)
                    .addComponent(non)
                    .addComponent(jLabel2)
                    .addComponent(bnDelete))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnUpddate))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 210, 200));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Traitement des Réclamations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), java.awt.Color.darkGray)); // NOI18N

        listeTraitement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Etudiant", "Reclamation", "Statut", "Commentaire"
            }
        ));
        listeTraitement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeTraitementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeTraitement);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentActionPerformed

    private void ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ouiActionPerformed

    private void nonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonActionPerformed

    private void bnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddActionPerformed
        EStatut statut = null;
        if (oui.isSelected()) {
            statut = EStatut.TRAITEE;
        } else {
            statut = EStatut.NON_TRAITEE;
        }
        String commentaire = txtComment.getText().toString();
        Reclamation reclamation = (Reclamation) listeReclamation.getSelectedItem();
        Etudiant etudiant = (Etudiant) listeEtudiant.getSelectedItem();

        if (trs.create(new TraitementReclamation(statut, commentaire, reclamation, etudiant))) {
            JOptionPane.showMessageDialog(this, "bien enregistrée");
            Load();
        } else {
            JOptionPane.showMessageDialog(this, "Probléme");
        }

    }//GEN-LAST:event_bnAddActionPerformed

    private void bnUpddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnUpddateActionPerformed
        int selectedRow = listeTraitement.getSelectedRow();

        if (selectedRow != -1) {
            int response = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier cette réclamation ?");

            if (response == JOptionPane.YES_OPTION) {
                Etudiant etudiant = (Etudiant) listeEtudiant.getSelectedItem();
                Reclamation reclamation = (Reclamation) listeReclamation.getSelectedItem();
                EStatut statut = oui.isSelected() ? EStatut.TRAITEE : EStatut.NON_TRAITEE;
                String commentaire = txtComment.getText();

                TraitementReclamation traitement = new TraitementReclamation(statut, commentaire, reclamation, etudiant);
                if (trs.update(traitement)) {
                    JOptionPane.showMessageDialog(this, "Modification réussie");
                    Load();
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de la modification");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une réclamation à modifier.");
        }
    }//GEN-LAST:event_bnUpddateActionPerformed

    private void listeTraitementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeTraitementMouseClicked
        int selectedRow = listeTraitement.getSelectedRow();
        if (selectedRow != -1) {
            Etudiant etudiant = (Etudiant) model.getValueAt(selectedRow, 0);
            Reclamation reclamation = (Reclamation) model.getValueAt(selectedRow, 1);
            EStatut statut = (EStatut) model.getValueAt(selectedRow, 2);
            String commentaire = model.getValueAt(selectedRow, 3).toString();

            // Set the retrieved values in form fields
            listeEtudiant.setSelectedItem(etudiant);
            listeReclamation.setSelectedItem(reclamation);
            txtComment.setText(commentaire);

            if (statut == EStatut.TRAITEE) {
                oui.setSelected(true);
            } else {
                non.setSelected(true);
            }
        }
    }//GEN-LAST:event_listeTraitementMouseClicked

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
        int selectedRow = listeTraitement.getSelectedRow();

        if (selectedRow != -1) {
            int response = JOptionPane.showConfirmDialog(this,
                    "Voulez-vous vraiment supprimer ce traitement de réclamation ?",
                    "Confirmation", JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
                Etudiant etudiant = (Etudiant) model.getValueAt(selectedRow, 0);
                Reclamation reclamation = (Reclamation) model.getValueAt(selectedRow, 1);
                EStatut statut = (EStatut) model.getValueAt(selectedRow, 2);
                String commentaire = model.getValueAt(selectedRow, 3).toString();

                TraitementReclamation traitement = new TraitementReclamation(statut, commentaire, reclamation, etudiant);

                if (trs.delete(traitement)) {
                    JOptionPane.showMessageDialog(this, "Suppression réussie");
                    Load(); // Recharger les données
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de la suppression");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un traitement de réclamation à supprimer.");
        }
    }//GEN-LAST:event_bnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnAdd;
    private javax.swing.JButton bnDelete;
    private javax.swing.JButton bnUpddate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listeEtudiant;
    private javax.swing.JComboBox listeReclamation;
    private javax.swing.JTable listeTraitement;
    private javax.swing.JRadioButton non;
    private javax.swing.JRadioButton oui;
    private javax.swing.JTextField txtComment;
    // End of variables declaration//GEN-END:variables
}
